// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: api/proto/customer.proto

package customerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idn           string                 `protobuf:"bytes,1,opt,name=idn,proto3" json:"idn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertCustomerRequest) Reset() {
	*x = UpsertCustomerRequest{}
	mi := &file_api_proto_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertCustomerRequest) ProtoMessage() {}

func (x *UpsertCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertCustomerRequest.ProtoReflect.Descriptor instead.
func (*UpsertCustomerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_customer_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertCustomerRequest) GetIdn() string {
	if x != nil {
		return x.Idn
	}
	return ""
}

type GetCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idn           string                 `protobuf:"bytes,1,opt,name=idn,proto3" json:"idn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerRequest) Reset() {
	*x = GetCustomerRequest{}
	mi := &file_api_proto_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerRequest) ProtoMessage() {}

func (x *GetCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_customer_proto_rawDescGZIP(), []int{1}
}

func (x *GetCustomerRequest) GetIdn() string {
	if x != nil {
		return x.Idn
	}
	return ""
}

type CustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Idn           string                 `protobuf:"bytes,2,opt,name=idn,proto3" json:"idn,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerResponse) Reset() {
	*x = CustomerResponse{}
	mi := &file_api_proto_customer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerResponse) ProtoMessage() {}

func (x *CustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_customer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerResponse.ProtoReflect.Descriptor instead.
func (*CustomerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_customer_proto_rawDescGZIP(), []int{2}
}

func (x *CustomerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomerResponse) GetIdn() string {
	if x != nil {
		return x.Idn
	}
	return ""
}

func (x *CustomerResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_api_proto_customer_proto protoreflect.FileDescriptor

const file_api_proto_customer_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/customer.proto\x12\bcustomer\")\n" +
	"\x15UpsertCustomerRequest\x12\x10\n" +
	"\x03idn\x18\x01 \x01(\tR\x03idn\"&\n" +
	"\x12GetCustomerRequest\x12\x10\n" +
	"\x03idn\x18\x01 \x01(\tR\x03idn\"S\n" +
	"\x10CustomerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03idn\x18\x02 \x01(\tR\x03idn\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt2\xa9\x01\n" +
	"\x0fCustomerService\x12M\n" +
	"\x0eUpsertCustomer\x12\x1f.customer.UpsertCustomerRequest\x1a\x1a.customer.CustomerResponse\x12G\n" +
	"\vGetCustomer\x12\x1c.customer.GetCustomerRequest\x1a\x1a.customer.CustomerResponseB0Z.shipment-customer-service/api/proto;customerpbb\x06proto3"

var (
	file_api_proto_customer_proto_rawDescOnce sync.Once
	file_api_proto_customer_proto_rawDescData []byte
)

func file_api_proto_customer_proto_rawDescGZIP() []byte {
	file_api_proto_customer_proto_rawDescOnce.Do(func() {
		file_api_proto_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_customer_proto_rawDesc), len(file_api_proto_customer_proto_rawDesc)))
	})
	return file_api_proto_customer_proto_rawDescData
}

var file_api_proto_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_customer_proto_goTypes = []any{
	(*UpsertCustomerRequest)(nil), // 0: customer.UpsertCustomerRequest
	(*GetCustomerRequest)(nil),    // 1: customer.GetCustomerRequest
	(*CustomerResponse)(nil),      // 2: customer.CustomerResponse
}
var file_api_proto_customer_proto_depIdxs = []int32{
	0, // 0: customer.CustomerService.UpsertCustomer:input_type -> customer.UpsertCustomerRequest
	1, // 1: customer.CustomerService.GetCustomer:input_type -> customer.GetCustomerRequest
	2, // 2: customer.CustomerService.UpsertCustomer:output_type -> customer.CustomerResponse
	2, // 3: customer.CustomerService.GetCustomer:output_type -> customer.CustomerResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_customer_proto_init() }
func file_api_proto_customer_proto_init() {
	if File_api_proto_customer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_customer_proto_rawDesc), len(file_api_proto_customer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_customer_proto_goTypes,
		DependencyIndexes: file_api_proto_customer_proto_depIdxs,
		MessageInfos:      file_api_proto_customer_proto_msgTypes,
	}.Build()
	File_api_proto_customer_proto = out.File
	file_api_proto_customer_proto_goTypes = nil
	file_api_proto_customer_proto_depIdxs = nil
}
